// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: query.sql

package database

import (
	"context"
)

const addLink = `-- name: AddLink :exec
INSERT INTO links (link, shortened_link)
VALUES (?, ?)
`

type AddLinkParams struct {
	Link          string
	ShortenedLink string
}

func (q *Queries) AddLink(ctx context.Context, arg AddLinkParams) error {
	_, err := q.db.ExecContext(ctx, addLink, arg.Link, arg.ShortenedLink)
	return err
}

const getFullLink = `-- name: GetFullLink :one
SELECT link
FROM links
WHERE shortened_link = (?)
ORDER BY link_id DESC
LIMIT 1
`

func (q *Queries) GetFullLink(ctx context.Context, shortenedLink string) (string, error) {
	row := q.db.QueryRowContext(ctx, getFullLink, shortenedLink)
	var link string
	err := row.Scan(&link)
	return link, err
}
